---
title: "Analysis_M"
author: "Matilde Jacobsen"
date: "10/20/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
Setup
```{r setup, include=FALSE}
#Load!
pacman::p_load(readr,tidyverse,dplyr,ggplot2,pastecs,ez,reshape2,stringr,lme4,stats,MuMIn,broom,emmeans,afex,lmerTest,scales,rstatix,ggpubr,magrittr,stats)
```

#Loading the data
```{r}
color_matching <- read.csv("Cleaned_data/color_matching.csv")
color_naming <- read.csv("Cleaned_data/color_naming.csv")

```


#Exploratory
Some things me and Hania tested Sunday the 18/10
```{r}
color_matching[1,12]

color_matching <- color_matching %>% 
  group_by(Generation, seed_color) %>% 
  filter(source_color.h) %>% 
  mutate(dh = min(abs(h_matching-h_seed), 360-abs(h_matching-h_seed)/180.0))



h_seed <- color_matching %>% group_by(Generation, seed_color) %>% filter(source_color.h)
h_matching <- color_matching %>% group_by(generation, seed_color) %>% filter(color.h)
dh = min(abs(h_matching-h_seed), 360-abs(h_matching-h_seed)/180.0)
```

#Eva's code

Hues defined
```{r}
#Hues of each color 
red <- 12.2
yellow <- 62.4
green <- 136.5
blue <- 193.6

#Hues of seed colors
reddish <- 327.55
yellowish <- 49.85
greenish <- 117.98
blueish <- 179.34

```

Data loading and preprocessing test data
```{r}
#Load test data
Test2 <- read_csv("Test2.csv")

#As factors 
Test2$Condition <- as.factor(Test2$Condition)
Test2$Chain <- as.factor(Test2$Chain)
Test2$Color <- as.factor(Test2$Color)


#Add column with difference between matched hue and focal:
Test2$Abs_Dif <- Test2$Focal-Test2$Hue

#Ass column with relative difference between matched hue and focal:
Test2$Rel_Dif <- 100/(Test2$Focal-Test2$Seed)*Test2$Abs_Dif

View(Test2)

```

Modelling test data
```{r}

#NB: The is a datapoint included for each chain with the seed coordinates (not a matching). Should no be included IRL.

#Saturation
require(afex)
set_sum_contrasts()
mm1 <- lmer(Saturation ~ Condition + Generation + Color + (0 + Chain|Generation), data = Test2, REML = F, control = lmerControl(
  optimizer = "nloptwrap",
  calc.derivs = F,
  optCtrl = list(
    ftol_abs = 1e-10,
    xtol_abs = 1e-10,
    maxeval = 10000
  )))
summary(mm1)

#Hue angle
#What is the matter with 0 or 1 in random effects? 
require(afex)
set_sum_contrasts()
mm2 <- lmer(Rel_Dif ~ Condition + Generation + Color + (0 + Chain|Generation), data = Test2, REML = F, control = lmerControl(
  optimizer = "nloptwrap",
  calc.derivs = F,
  optCtrl = list(
    ftol_abs = 1e-10,
    xtol_abs = 1e-10,
    maxeval = 10000
  )))
summary(mm2)

```

Visualizations
```{r}
#Omit rows with NAs
Test2 <- na.omit(Test2)

#Hue
ggplot(Test2,aes(Generation, Rel_Dif))+geom_point()

#Saturation
ggplot(Test2,aes(Generation, Saturation))+geom_point()

#Boxplots
color_sat <- ggboxplot(
  Test2, x = "Color", y = "Saturation",
  color = "Condition", palette = "jco"
  )
color_sat

color_hue <- ggboxplot(
  Test2, x = "Color", y = "Rel_Dif",
  color = "Condition", palette = "jco"
  )
color_hue

cond_sat <- ggboxplot(
  Test2, x = "Condition", y = "Saturation",
  color = "Color", palette = "jco"
  )
cond_sat

cond_hue <- ggboxplot(
  Test2, x = "Condition", y = "Rel_Dif",
  color = "Color", palette = "jco"
  )
cond_hue

#Trying out a line plot
color_sat_line <- ggplot(Test2, aes(x=Generation,y=Saturation,group=Color))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generations") + ylab("Saturation %") +
  ggtitle("Plot")
color_sat_line

color_hue_line <- ggplot(Test2, aes(x=Generation,y=Rel_Dif,group=Color))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + ylab("Relative difference %") +
  ggtitle("Plot")
color_hue_line

cond_sat_line <- ggplot(Test2, aes(x=Generation,y=Saturation,group=Condition))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generations") + ylab("Saturation %") +
  ggtitle("Plot")
cond_sat_line

cond_hue_line <- ggplot(Test2, aes(x=Generation,y=Rel_Dif,group=Condition))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + ylab("Relative difference %") +
  ggtitle("Plot")
cond_hue_line


```


#Using real data

NB: should be moved to data cleaning
```{r}
#adding column color
# color_matching <- color_matching %>% 
#   mutate(Color = case_when(
#           between(source_color.h, 5, 93) ~ "mustard",
#           between(source_color.h, 112, 152) ~ "grass green",
#           between(source_color.h, 170, 200) ~ "ocean blue",
#           between(source_color.h, 300, 340) ~ "dark rose"))

#adding column focal
color_matching <- color_matching %>% 
  mutate(Focal = case_when(
          Color_label_matched == "seed mustard" ~ yellow,
          Color_label_matched == "seed grass green" ~ green,
          Color_label_matched == "seed ocean blue" ~ blue,
          Color_label_matched == "seed dark rose" ~ red))


#As factors cleaned
color_matching$Condition <- as.factor(color_matching$Condition)
color_matching$Chain <- as.factor(color_matching$Chain)
color_matching$Color_label_matched <- as.factor(color_matching$Color_label_matched) #something we don't have yet


#Add column with difference between matched hue and focal:
color_matching$Abs_Dif <- color_matching$Focal-color_matching$Hue_matched

#trying to solve problem with red
color_matching$Abs_Dif2 <- min(abs(color_matching$Focal-color_matching$Hue_matched), 360-abs(color_matching$Focal-color_matching$Hue_matched)/180.0)


#skal give 34.2
min(abs(12.2 - 278), 360-abs(12.2 - 278)/180)
360-265.8
?min

#Add column with relative difference between matched hue and focal:
color_matching$Rel_Dif <- 100/(color_matching$Focal-color_matching$source_color.h)*color_matching$Abs_Dif

```


Modelling cleaned data
NB: does not have enough data yet...
```{r}

#Very simple model
simple_m_sat <- lm(Saturation_matched ~ Generation + Color_label_matched, data = color_matching)
summary(simple_m_sat)

simple_m_hue <- lm(Rel_Dif ~ Generation + Color_label_matched, data = color_matching)
summary(simple_m_hue)

#NB: The is a datapoint included for each chain with the seed coordinates (not a matching). Should no be included IRL.

#Saturation
require(afex)
set_sum_contrasts()
model1 <- lmer(color.s ~ Condition + Generation + Color + (0 + Chain|Generation), data = color_matching, REML = F, control = lmerControl(
  optimizer = "nloptwrap",
  calc.derivs = F,
  optCtrl = list(
    ftol_abs = 1e-10,
    xtol_abs = 1e-10,
    maxeval = 10000
  )))
summary(model1)

#Hue angle
#What is the matter with 0 or 1 in random effects? 
require(afex)
set_sum_contrasts()
model2 <- lmer(Rel_Dif ~ Condition + Generation + Color + (0 + Chain|Generation), data = color_matching, REML = F, control = lmerControl(
  optimizer = "nloptwrap",
  calc.derivs = F,
  optCtrl = list(
    ftol_abs = 1e-10,
    xtol_abs = 1e-10,
    maxeval = 10000
  )))
summary(mm2)

```

