---
title: "BA analysis test"
author: "Eva SH"
date: "10/14/2020"
output: html_document
---

Setup
```{r setup, include=FALSE}
#Load
pacman::p_load(readr,dplyr)
```

Loading and some extra wrangling
```{r}
setwd("~/Desktop/Cognitive Science/Bachelor/Test data and code/analysis")

###WE NEED TO FIND A SOLUTION WITH RED: IF STATEMENT FOR HUES BETWEEN 0 AND 20? But it works with the current data right now. Think it works. 

data <- read_csv("color_matching2020-10-31.csv")

#As factors
data$Subject <- as.factor(data$Subject)
data$Language <- as.factor(data$Language)
data$Gender <- as.factor(data$Gender)
data$Language_spoken <- as.factor(data$Language_spoken)
data$Condition <- as.factor(data$Condition)
data$Chain <- as.factor(data$Chain)
data$Color_label_source <- as.factor(data$Color_label_source)
data$Color_label_matched <- as.factor(data$Color_label_matched)
data$Age <- as.numeric(data$Age)

# #Create column with native language combined: Danish, English, Danish bilingual and other
# data$Language_class <- revalue(data$Language_spoken,c("dansk" = "Danish", "danish" = "Danish","dansker" = "Danish","Dansk" = "Danish","DK"="Danish","Engelsk" = "English", "EnglishandArabic" = "English", "DanskEngelsk" = "Bilingual", "Danskfransk" = "Bilingual", "DanskogBosnisk" = "Bilingual","Danskogengelsk" = "Bilingual", "Danskogsomalisk" = "Bilingual", "NederlandskDansk" = "Bilingual", "Dansksomalisk" = "Bilingual", "Albansk" = "Other", "Croatian" = "Other", "Czech" = "Other", "Estonian" = "Other", "Fransk" = "Other", "geman" = "Other", "German" = "Other", "GermanAfrikaans" = "Other", "Greek" = "Other", "Hollandsk" = "Other", "ita" = "Other", "Lithuanian" = "Other", "Lykke" = "Other", "Polish" = "Other", "polish" = "Other", "portuguese" = "Other", "Romanian" = "Other", "rumænsk" = "Other", "Russian" = "Other", "somalisk" = "Other", "spanish" = "Other", "Spanish" = "Other", "Svensk" = "Other", "Swedish" = "Other", "Ukrainian" = "Other", "Ungarsk" = "Other"))

#Remove chain 5
data <- data %>% filter(!Chain=="5")
```

Subsets
```{r}
#Datasets divided into Danish and English
danish <- data %>% filter(Language == "Danish")
english <- data %>% filter(Language == "English")

#Subset for each condition
cond1_danish <- danish %>% filter(Condition==1)
cond2_danish <- danish %>% filter(Condition==2)
cond1_english <- english %>% filter(Condition==1)
cond2_english <- english %>% filter(Condition==2)

#Subsets by color
d_red <- danish %>% filter(Color_label_matched == "seed dark rose")
d_yellow <- danish %>% filter(Color_label_matched == "seed mustard")
d_green <- danish %>% filter(Color_label_matched == "seed grass green")
d_blue <- danish %>% filter(Color_label_matched == "seed ocean blue")

#Subsets by color AND condition
d_red_cond1 <- d_red %>% filter(Condition=="1")
d_red_cond2 <- d_red %>% filter(Condition=="2")
d_yellow_cond1 <- d_yellow %>% filter(Condition=="1")
d_yellow_cond2 <- d_yellow %>% filter(Condition=="2")
d_green_cond1 <- d_green %>% filter(Condition=="1")
d_green_cond2 <- d_green %>% filter(Condition=="2")
d_blue_cond1 <- d_blue %>% filter(Condition=="1")
d_blue_cond2 <- d_blue %>% filter(Condition=="2")

```


Descriptive statistics
```{r}
#Hue
danish %>% 
  group_by(Chain, Condition,Color_label_matched) %>% 
  summarise(max(Rel_dif),min(Rel_dif),mean(Hue_matched)) %>% 
  arrange(Color_label_matched)

#Saturation
danish %>% 
  group_by(Chain, Condition,Color_label_matched) %>% 
  summarise(max(Saturation_matched),min(Saturation_matched),mean(Saturation_matched))
```



Demographics
```{r}
#Load
pacman::p_load(readr,tidyverse,ggplot2,pastecs,ez,reshape2,stringr,lme4,stats,MuMIn,broom,emmeans,afex,lmerTest,scales,rstatix,ggpubr,magrittr,stats)

#Dataframe with 1 row pr subject 
unique <- data[ !duplicated(data$Subject,fromLast=TRUE), ]
unique_danish <- danish[ !duplicated(danish$Subject,fromLast=TRUE), ]
unique_english <- english[ !duplicated(english$Subject,fromLast=TRUE), ]

#In each language
unique %>% count("Language")

#Conditions
unique_danish %>% count("Condition") 
unique_english %>% count("Condition") 

#Gender
#Across conditions
unique_danish %>% count("Gender") 
(100/153) * 85
(100/153) * 68
unique_english %>% count("Gender")
(100/32) * 15
(100/32) * 17

#For each condition
unique_danish %>% filter(Condition=="1") %>% count("Gender") 
(100/78) * 46
(100/78) * 32
unique_danish %>% filter(Condition=="2") %>% count("Gender")
(100/75) * 39 
(100/75) * 36

unique_english %>% filter(Condition=="1") %>% count("Gender") 
(100/16) * 4
(100/16) * 12
unique_english %>% filter(Condition=="2") %>% count("Gender") 
(100/16) * 11
(100/16) * 5

#Age
#Across condition
unique_danish %>% get_summary_stats(Age,type = "mean_sd")
unique_english %>% get_summary_stats(Age,type = "mean_sd")

#For each condition
unique_danish %>% filter(Condition=="1") %>% get_summary_stats(Age,type = "mean_sd")
unique_danish %>% filter(Condition=="2") %>% get_summary_stats(Age,type = "mean_sd")
unique_english %>% filter(Condition=="1") %>% get_summary_stats(Age,type = "mean_sd")
unique_english %>% filter(Condition=="2") %>% get_summary_stats(Age,type = "mean_sd")

#Native languages
#Across conditions
unique_danish %>% count("Language_class")
(100/153) * 136
(100/153) * 1
(100/153) * 7
(100/153) * 9
unique_english %>% count("Language_class")
(100/32) * 22
(100/32) * 5

#For each condition
unique_danish %>%  filter(Condition=="1") %>% count("Language_class")
100/78 * 66
100/78 * 4
100/78 * 8
unique_danish %>%  filter(Condition=="2") %>% count("Language_class")
100/75 * 70
100/75 * 1
100/75 * 3

unique_english %>%  filter(Condition=="1") %>% count("Language_class")
100/16 * 11
100/16 * 2
100/16 * 3
unique_english %>%  filter(Condition=="2") %>% count("Language_class")

```

Plots
```{r}
#CONDITION 1
cond_1_hue <- ggplot(cond1_danish, aes(x = Generation, y = Rel_dif, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Relative difference %") +
  ggtitle("Plot") +
  facet_wrap(~ Color_label_source)
cond_1_hue

cond_1_sat <- ggplot(cond1_danish, aes(x = Generation, y = Saturation_matched, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Saturation %") +
  ggtitle("Plot") +
  facet_wrap(~ Color_label_source)
cond_1_sat

#CONDITION 2
cond_2_hue <- ggplot(cond2_danish, aes(x = Generation, y = Rel_dif, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Relative difference %") +
  ggtitle("Plot") +
  facet_wrap(~ Color_label_source)
cond_2_hue

cond_2_sat <- ggplot(cond2_danish, aes(x = Generation, y = Saturation_matched, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Saturation %") +
  ggtitle("Plot") +
  facet_wrap(~ Color_label_source)
cond_2_sat

#ENGLISH
english_hue <- ggplot(english, aes(x = Generation, y = Rel_dif, group = Condition, color = Condition))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Relative difference %") +
  ggtitle("Plot") +
  facet_wrap(~ Color_label_source)
english_hue

english_sat <- ggplot(english, aes(x = Generation, y = Saturation_matched, group = Condition, color = Condition))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Saturation %") +
  ggtitle("Plot") +
  facet_wrap(~ Color_label_source)
english_sat



#Considerations from plot-viewing: 
#Consider looking for whether participant 1 chooses approximate the same difference from start hue and saturation for each different color (seems like it)


#RED
red_hue<- ggplot(red, aes(x = Generation, y = Rel_dif, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Relative difference %") +
  ggtitle("Plot") +
  facet_wrap(~ Condition)
red_hue

red_sat <- ggplot(red, aes(x = Generation, y = Saturation_matched, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Saturation %") +
  ggtitle("Plot") +
  facet_wrap(~ Condition)
red_sat

#YELLOW
yellow_hue <- ggplot(yellow, aes(x = Generation, y = Rel_Dif, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Relative difference %") +
  ggtitle("Plot") +
  facet_wrap(~ Condition)
yellow_hue

yellow_sat <- ggplot(yellow, aes(x = Generation, y = Saturation_matched, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Saturation %") +
  ggtitle("Plot") +
  facet_wrap(~ Condition)
yellow_sat

#GREEN
green_hue <- ggplot(green, aes(x = Generation, y = Rel_Dif, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Relative difference %") +
  ggtitle("Plot") +
  facet_wrap(~ Condition)
green_hue

green_sat <- ggplot(green, aes(x = Generation, y = Saturation_matched, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Saturation %") +
  ggtitle("Plot") +
  facet_wrap(~ Condition)
green_sat

#BLUE
blue_hue <- ggplot(blue, aes(x = Generation, y = Rel_Dif, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Relative difference %") +
  ggtitle("Plot") +
  facet_wrap(~ Condition)
blue_hue

blue_sat <- ggplot(blue, aes(x = Generation, y = Saturation_matched, group = Chain, color = Chain))+
  geom_line(stat="summary") +
  expand_limits(y=0) +
  xlab("Generation") + 
  ylab("Saturation %") +
  ggtitle("Plot") +
  facet_wrap(~ Condition)
blue_sat

```

Normality checks
```{r}

#Normality (Shapiro-Wilks)
danish %>% group_by(Chain, Condition, Color_label_matched) %>% shapiro_test(Rel_dif)
ggqqplot(danish, "Rel_dif", ggtheme = theme_bw()) +
  facet_grid(Condition + Color_label_matched ~ Chain, labeller = "label_both")

danish %>% group_by(Chain, Condition, Color_label_matched) %>% shapiro_test(Saturation_matched)
ggqqplot(danish, "Saturation_matched", ggtheme = theme_bw()) +
  facet_grid(Condition + Color_label_matched ~ Chain, labeller = "label_both")

```

Modelling
```{r}
#Saturation 
model1 <- lmer(
  Saturation_matched ~ Generation + Condition + Generation:Condition + 
  (0 + Generation + Condition + Generation:Condition | Color_label_matched) +
  (0 + Generation + Condition + Generation:Condition | Chain) + 
  (0 + Generation + Condition + Generation:Condition | Chain:Subject), 
  data = danish, 
  REML = F, control = lmerControl(
  optimizer = "nloptwrap",
  calc.derivs = F,
  check.nobs.vs.nRE = "ignore",
  optCtrl = list(
    ftol_abs = 1e-10, 
    xtol_abs = 1e-10,
    maxeval = 10000
  )))
summary(model1)

#Relative hue difference
model2 <- lmer(
  Rel_dif ~ Generation + Condition + Generation:Condition +
  (0 + Generation + Condition + Generation:Condition | Color_label_matched) + 
  (0 + Generation + Condition + Generation:Condition| Chain) +
  (0 + Generation + Condition + Generation:Condition| Chain:Subject),
  data = danish, 
  REML = F, control = lmerControl(
  optimizer = "nloptwrap",
  calc.derivs = F,
  check.nobs.vs.nRE = "ignore",
  optCtrl = list(
    ftol_abs = 1e-10,
    xtol_abs = 1e-10,
    maxeval = 10000
  )))
summary(model2)


#Effect of color
model3 <- lm(Rel_dif ~ 0 + Color_label_matched * Generation, data = danish)
summary(model3)

model4 <- lm(Saturation_matched ~ 0 + Color_label_matched * Generation, data = danish)
summary(model4)

#Effect of color in interaction with condition
model5 <- lm(Rel_dif ~ 0 + Color_label_matched * Generation * Condition, data = danish)
summary(model5)

model6 <- lm(Saturation_matched ~ 0 + Color_label_matched * Generation * Condition, data = danish)
summary(model6)

```

Exploratory analyses
```{r}
#Correlation between change in saturation and hue angle? 

#Convergence towards other focals 
  #Find focal measure in HSL

#Increased levels of confidence predicts accuracy


```

















